---
title: "Palmer Drought Severity Index"
author: "AnnaClaire Marley"
date: "7/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
# load the packages
library(tidyverse)
library(janitor)
library(lubridate)
library(gridExtra)
library(grid)
library(dataRetrieval)
library(reshape2)
library(corrplot)
source("Functions/util.R")
source('Functions/graphing.R')
```

```{r, include = FALSE}
# read in NN whole PDSI

nn_pdsi <- read_csv("NN_whole/nn_pdsi_79-19.csv") %>% 
  rename(date = DateTime,
         pdsi = `Palmer Drought Severity Index (PDSI) (gridMET) at 4005, 1979-01-01 to 2019-06-09`) %>% 
  add_water_year()


```


```{r, include = FALSE}

# read in the agency data & add water year
chinle_pdsi <- read_csv("Agencies/chinle_pdsi.csv") 
east_navajo_pdsi <- read_csv("Agencies/east_navajo_pdsi.csv")
west_navajo_pdsi <- read_csv("Agencies/west_navajo_pdsi.csv")
shiprock_pdsi <- read_csv("Agencies/shiprock_pdsi.csv")
fort_defiance_pdsi <- read_csv("Agencies/fort_defiance_pdsi.csv")

# winter months
chinle_pdsi_wint <- chinle_pdsi %>% 
  filter(month(date) %in% c(11, 12, 1, 2, 3, 4))

east_navajo_pdsi_wint <- east_navajo_pdsi %>% 
  filter(month(date) %in% c(11, 12, 1, 2, 3, 4))

west_navajo_pdsi_wint <- west_navajo_pdsi %>% 
  filter(month(date) %in% c(11, 12, 1, 2, 3, 4))

shiprock_pdsi_wint <- shiprock_pdsi %>% 
  filter(month(date) %in% c(11, 12, 1, 2, 3, 4))

fort_defiance_pdsi_wint <- fort_defiance_pdsi %>% 
  filter(month(date) %in% c(11, 12, 1, 2, 3, 4))

```

```{r, include = FALSE}
# take the average yearly pdsi value 
chinle_an_av <- calc_pdsi_metrics(chinle_pdsi, "year", mean)
east_navajo_an_av <- calc_pdsi_metrics(east_navajo_pdsi, "year", mean)
west_navajo_an_av <- calc_pdsi_metrics(west_navajo_pdsi, "year", mean)
shiprock_an_av <- calc_pdsi_metrics(shiprock_pdsi, "year", mean)
fort_defiance_an_av <- calc_pdsi_metrics(fort_defiance_pdsi, "year", mean)

# take the monthly mean of the yearly data

chinle_mnth_av <- calc_pdsi_metrics(chinle_pdsi, "month", mean)
east_navajo_mnth_av <- calc_pdsi_metrics(east_navajo_pdsi, "month", mean)
west_navajo_mnth_av <- calc_pdsi_metrics(west_navajo_pdsi, "month", mean)
shiprock_mnth_av <- calc_pdsi_metrics(shiprock_pdsi, "month", mean)
fort_defiance_mnth_av <- calc_pdsi_metrics(fort_defiance_pdsi, "month", mean)

# take the monthly mean of the winter data
chinle_mnth_av_wint <- calc_pdsi_metrics(chinle_pdsi_wint, "month", mean)
east_navajo_mnth_av_wint <- calc_pdsi_metrics(east_navajo_pdsi_wint, "month", mean)
west_navajo_mnth_av_wint <- calc_pdsi_metrics(west_navajo_pdsi_wint, "month", mean)
shiprock_mnth_av_wint <- calc_pdsi_metrics(shiprock_pdsi_wint, "month", mean)
fort_defiance_mnth_av_wint <- calc_pdsi_metrics(fort_defiance_pdsi_wint, "month", mean)

# visualize example 
ggplot(chinle_mnth_av_wint, aes(x = date, y = pdsi)) +
  geom_col() +
  theme_classic()

```


#### Correlation of PDSI monthly averages for the Agencies
```{r, echo = FALSE}
## look to see how correlated the PDSI is between regions

pdsi_agencies <- chinle_mnth_av %>% 
  rename(chinle = pdsi) %>% 
  left_join(east_navajo_mnth_av, by = "date") %>% 
  rename(east_navajo = pdsi) %>% 
  left_join(west_navajo_mnth_av, by = "date") %>% 
  rename(west_navajo = pdsi) %>% 
  left_join(shiprock_mnth_av, by = "date") %>% 
  rename(shiprock = pdsi) %>% 
  left_join(fort_defiance_mnth_av, by = "date") %>% 
  rename(fort_defiance = pdsi) %>% 
  select(date, chinle, east_navajo, west_navajo, shiprock, fort_defiance) 
  
pdsi_cor_df<- pdsi_agencies %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "date")

# correlation matrix
cor_pdsi <- cor(pdsi_cor_df)
corrplot(cor_pdsi, method = "ellipse", type = "upper", 
         addCoef.col = "black", tl.col = "black",  tl.srt=45)

```



```{r, echo=FALSE}
#### Now look to see if there are correlations in PDSI and swe levels ####

# first read in Chuska swe data and calculate metrics

chuska_swe <- read_csv("winter_wy/ch_swe_wy_03_19.csv")
chuska_swe_mnth_av <- calc_swe_metrics(chuska_swe, "month", mean)
chuska_swe_an_av <- calc_swe_metrics(chuska_swe, "year", mean)
chuska_mnth_anom <- calc_month_anom(chuska_swe_mnth_av) %>% 
  arrange(date)

# plot swe vs pdsi

plot(shiprock_mnth_av_wint$pdsi, chuska_mnth_anom$anomaly)
cor.test(shiprock_an_av$pdsi, chuska_swe_an_av$swe_mm)
```

```{r}
## see how chuska correlates with the pdsi of the agencies

agencies_v_chuska <- pdsi_agencies %>% 
  left_join(chuska_swe_mnth_av, by = "date") %>% 
  select(-waterYear) %>% 
  filter(swe_mm != "NA") %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "date")

cor_pdsi_chuska <- cor(agencies_v_chuska)
corrplot(cor_pdsi_chuska, method = "ellipse", type = "upper", 
         addCoef.col = "black", tl.col = "black",  tl.srt=45)
```


```{r, echo = FALSE}



## make dataframes with swe and pdsi for shiprock

chuska_ship <- shiprock_mnth_av %>% 
  left_join(chuska_mnth_anom, by = "date") %>% 
  select(date, pdsi, anomaly, sign, waterYear.x, anomaly_perc) 

## make graph of the two
chuska_ship_graph <- chuska_ship %>% 
  ggplot(aes(x = date)) +
  geom_col(aes(y = anomaly_perc, fill = sign), show.legend = FALSE) +
  scale_fill_manual(values = c("negative" = "#df5e3d", "positive" = "#a6c39d")) +
  labs(
    y = "SWE Anomaly (scaled down by 10)"
  ) +
  geom_col(aes(y = pdsi), color = "#1219cc", alpha = 0.5) +
  scale_y_continuous(sec.axis = sec_axis(~.*5, name = "PDSI"), expand = c(0,0)) +
  theme_classic()

chuska_ship_graph



```

```{r, echo = FALSE}
# chuska vs chinle

chuska_chin <- chinle_mnth_av %>% 
  left_join(chuska_mnth_anom, by = "date") %>% 
  select(date, pdsi, anomaly, sign, waterYear.x) 

## make graph of the two
chuska_chin_graph <- chuska_chin %>% 
  ggplot(aes(x = date)) +
  geom_col(aes(y = anomaly / 10, fill = sign), show.legend = FALSE) +
  scale_fill_manual(values = c("negative" = "#df5e3d", "positive" = "#a6c39d")) +
  labs(
    y = "SWE Anomaly (scaled down by 10)"
  ) +
  geom_col(aes(y = pdsi), color = "#1219cc", alpha = 0.5) +
  scale_y_continuous(sec.axis = sec_axis(~.*5, name = "PDSI"), expand = c(0,0)) +
  theme_classic()

chuska_chin_graph

```

```{r, echo = FALSE}
#fortdefiance anomaly

fort_def_mnth_intra_av <- fort_defiance_mnth_av %>% 
    mutate(month = month(date)) %>% 
    group_by(month) %>% 
    summarize(mean_pdsi = mean(pdsi))
    
fort_def_anom  <- fort_defiance_mnth_av %>% 
    mutate(month = month(date)) %>% 
    merge(fort_def_mnth_intra_av, by = "month")%>%
    mutate(anomaly_pdsi = pdsi - mean_pdsi) %>% 
    mutate(pdsi_anom_perc = (anomaly_pdsi/mean_pdsi)*100)

# chuska vs fort defiance
chuska_fd <- fort_def_anom %>% 
  left_join(chuska_mnth_anom, by = "date") %>% 
  select(date, pdsi, anomaly, sign, waterYear.x, anomaly_pdsi, pdsi_anom_perc, anomaly_perc) 

## make graph of the two
chuska_fd_graph <- chuska_fd %>% 
  ggplot(aes(x = date)) +
  geom_col(aes(y = anomaly_perc, fill = sign), show.legend = FALSE) +
  scale_fill_manual(values = c("negative" = "#df5e3d", "positive" = "#a6c39d")) +
  labs(
    y = "SWE % Difference from Average"
  ) +
  geom_line(aes(y = anomaly_pdsi*100), color = "#1219cc", alpha = 0.5) +
  scale_y_continuous(sec.axis = sec_axis(~., name = "PDSI % Difference from Average"), expand = c(0,0)) +
  theme_classic()

chuska_fd_graph

chuska_fd_graph2 <- chuska_fd %>% 
  ggplot(aes(x = date)) +
  geom_col(aes(y = anomaly_perc, fill = sign), show.legend = FALSE) +
  scale_fill_manual(values = c("negative" = "#df5e3d", "positive" = "#a6c39d")) +
  labs(
    y = "SWE % Difference from Average",
    x = "Water Year"
  ) +
  geom_line(aes(y = anomaly_pdsi*100), color = "#1219cc", alpha = 0.5) +
  scale_y_continuous(sec.axis = sec_axis(~.*5, name = "PDSI Anomaly (scaled x 100)"), expand = c(0,0)) +
  scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
  theme_classic() +
  theme(axis.line.y.right = element_line(color = "#1219cc"),
        axis.text.y.right = element_text(color = "#1219cc"),
        axis.title.y.right = element_text(color = "#1219cc"))

chuska_fd_graph2


```

```{r, echo = FALSE}
# Chuska and fort defiance agency % difference from average correlations

plot(chuska_fd$anomaly_perc, chuska_fd$anomaly_pdsi)

cor.test(chuska_fd$anomaly_perc, chuska_fd$anomaly_pdsi)
```


```{r, echo = FALSE}
## quick make chuska anomaly graph for poster

 # first make variables for ease of graphing  
      startWaterYear = min(chuska_mnth_anom$waterYear)
      endWaterYear = max(chuska_mnth_anom$waterYear)
      # Create sequence of real dates, on which to place the water year lables
      breakDates = seq.Date(from = ymd(paste(startWaterYear,1,1, sep='-')), length.out = endWaterYear - startWaterYear + 1, by = "1 year")

ch_poster <- ggplot(chuska_mnth_anom, aes(x = date, y = anomaly)) +
  geom_col(aes(y = anomaly / 10, fill = sign), show.legend = FALSE) +
  scale_fill_manual(values = c("negative" = "#df5e3d", "positive" = "#a6c39d")) +
  scale_x_date(breaks= breakDates, labels=seq(startWaterYear,endWaterYear,by=1)) +
  labs(
    y = "SWE Anomaly (mm)",
    x = "Water Year"
  ) +
  theme_classic()

```


### PDSI Whole Navajo Nation
```{r, echo = FALSE}
# do some analysis of the whole NN

nn_wk_pdsi <- calc_pdsi_metrics(nn_pdsi, "1 week", mean)

nn_wk_pdsi_graph <- nn_wk_pdsi %>% 
  ggplot(aes(x = date, y = pdsi)) + 
  geom_line() +
  theme_classic()


```

```{r, echo = FALSE}
nn_mnth_pdsi <- calc_pdsi_metrics(nn_pdsi, "month", mean)

nn_mnth_pdsi_graph <- nn_mnth_pdsi %>% 
  ggplot(aes(x = date, y = pdsi)) + 
  geom_col(aes(fill = sign), show.legend = FALSE) +
  labs(
    x = "Year",
    y = "PDSI",
    title = "Navajo Nation Palmer Drought Severity Index (PDSI) "
  ) +
  scale_x_date(expand = c(0,0)) +
  scale_fill_manual(values = c("negative" = "#df5e3d", "positive" = "#a6c39d")) +
  geom_smooth(method = "lm") +
  theme_classic()

nn_mnth_pdsi_graph
```

#### Compare to total swe for all high elevation regions

```{r, echo = FALSE}
# read in the total weekly swe for the mountain ranges 
mtns_swe <- read_csv("NN_whole/nn_mtns_swe_total.csv")

# calculate monthly anomaly
mtns_swe_anom <- mtns_swe %>% 
  rename(swe_mm = sum_mts_swe_m3) %>% 
  add_water_year() %>% 
  calc_swe_metrics("month", mean) %>% 
  calc_month_anom() 
```

```{r, echo = FALSE}
#### graph percent difference from average swe against pdsi

#first merge both things into the same dataframe
mtns_swe_nn_pdsi <- left_join(nn_mnth_pdsi, mtns_swe_anom, by = "date") %>% 
  filter(date >= "2003-10-01") %>% 
  select(date, waterYear.x, anomaly_perc, sign.x,  pdsi, sign.y) %>% 
  rename(pdsi_sign = sign.x,
         swe_sign = sign.y)

# now graph it

nn_pdsi_swe <- mtns_swe_nn_pdsi %>% 
  ggplot(aes(x = date)) + 
  geom_col(aes(y = pdsi, fill = pdsi_sign), show.legend = FALSE) +
  labs(
    x = "Year",
    y = "PDSI",
    title = "Navajo Nation Palmer Drought Severity Index (PDSI) "
  ) +
  scale_x_date(expand = c(0,0)) +
  scale_fill_manual(values = c("negative" = "#df5e3d", "positive" = "#a6c39d")) +
  geom_col(aes(y = anomaly_perc/100, alpha = 0.5), fill = "#1219cc") +
  scale_y_continuous(sec.axis = sec_axis(~.*5, name = "SWE Anomaly (scaled down by 100)"), expand = c(0,0)) +
  scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
  theme_classic() +
  theme(axis.line.y.right = element_line(color = "#1219cc"),
        axis.text.y.right = element_text(color = "#1219cc"),
        axis.title.y.right = element_text(color = "#1219cc")) 
  

nn_pdsi_swe

```


