---
title: "Standardized Precipitation Index"
author: "AnnaClaire Marley"
date: "7/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
# load the packages
library(tidyverse)
library(janitor)
library(lubridate)
library(gridExtra)
library(grid)
library(dataRetrieval)
library(reshape2)
library(corrplot)
library(precintcon)
source("Functions/util.R")
source('Functions/graphing.R')
```

```{r, include = FALSE}
# read in TSAILE precipitation

tsaile_precip <- read_csv("Chapters/tsaile_precip.csv")

# now change the precip data to spi
tsaile_spi <- precip_to_spi(tsaile_precip)

```

```{r, echo = FALSE}

# let's take a look at SPI Jan-June of each year
tsaile_spi_graph <- tsaile_spi %>% 
  filter(month(date) == 6) %>% 
  filter(year(date) >= 2004) %>% 
  ggplot(aes(x = date)) +
  geom_col(aes(y = spi, fill = sign), show.legend = FALSE) +
  scale_fill_manual(values = c("negative" = "#df5e3d", "positive" = "#a6c39d")) +
  labs(
    y = "SPI"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  theme_classic()

tsaile_spi_graph

```

```{r, echo = FALSE}
### now let's look at Chuska monthly swe anomaly and Tsaile SPI Jan-June ###

# first load in chuska winter anomalies

ch_wint_anom <- read_csv("Chuska/ch_wint_swe_anom.csv") %>% 
  select(waterYear, anomaly_perc)

# clean up tsail_spi and combine with chuska
tsaile_spi_june <- tsaile_spi %>% 
  filter(year(date) >= 2004) %>% 
  filter(month(date) == 6) %>% 
  mutate(waterYear = year(date)) %>% 
  select(waterYear, spi, sign) 


# let's look at the winter chuska swe anom and the Jan-june SPI
ch_tsail_spi_plot <- tsaile_spi_june %>% 
  merge(ch_wint_anom, by = "waterYear") %>% 
  select(waterYear,anomaly_perc, spi) %>% 
  melt(id.vars = "waterYear") %>% 
  rename(metric = variable) %>% 
  ggplot(aes(x = waterYear, y = value, fill = metric)) +
  geom_col(position = "dodge") +
  theme_classic()

ch_tsail_spi_plot


```

- 7/10 of negative swe years followed by negative spi
- 4/6 of positive swe years followed by positive spi 

```{r, echo = FALSE}

# let's look at the correlation between them 
ch_tsaile_spi <- tsaile_spi_june %>% 
   merge(ch_wint_anom, by = "waterYear") %>% 
   rename(swe_anom = anomaly_perc)

plot_cor_swe_spi(ch_tsaile_spi, title = "Chuska Winter SWE Anomaly and Tsaile Jan-June SPI")

ch_tsaile_correct <- (count(filter(ch_tsaile_spi, spi < 0 & swe_anom < 0)) + count(filter(ch_tsaile_spi, spi > 0 & swe_anom > 0))) / count(ch_tsaile_spi)
```

The percent of times swe and pdsi had the same sign `r ch_tsaile_correct`
