---
title: "SWE_clean"
author: "AnnaClaire Marley"
date: "03/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
# load the packages
library(tidyverse)
library(janitor)
library(lubridate)
library(gridExtra)
library(grid)
library(dataRetrieval)
source("Functions/util.R")
source('Functions/graphing.R')
```

```{r, include = FALSE}
# read in the data:
carrizo <- read_csv("Carrizo/carrizo_swe_03_19.csv") 
chuska <- read_csv("Chuska/chuska_swe_03_19.csv")
black_mesa <- read_csv("Black Mesa/BM_swe_03_19.csv")
```


```{r, include = FALSE}
# clean and make it just winter data
car_wint_cal <- extract_winter_months(carrizo)
ch_wint_cal <- extract_winter_months(chuska)
bm_wint_cal <- extract_winter_months(black_mesa)

# Adds water year. Renames column date to Date
car_wint_wy <- add_water_year(car_wint_cal)
ch_wint_wy <- add_water_year(ch_wint_cal)
bm_wint_wy <- add_water_year(bm_wint_cal)
```

## Daily SWE variability November - April 
```{r, fig.width=20,fig.height=5}
carr_daily <- graph_SWE_with_wateryear(car_wint_wy, "Carrizo")
carr_daily
```

```{r, fig.width=20,fig.height=5}
ch_daily <- graph_SWE_with_wateryear(ch_wint_wy, "Chuska")
ch_daily
```

```{r, fig.width=20,fig.height=5}
bm_daily <- graph_SWE_with_wateryear(bm_wint_wy, "Black Mesa")
bm_daily
```
```{r}
# create the monthly mean dataframes
carr_monthly <- calc_swe_metrics(car_wint_wy, "month", mean)
ch_monthly <- calc_swe_metrics(ch_wint_wy, "month", mean)
bm_monthly <- calc_swe_metrics(bm_wint_wy, "month", mean)
```

```{r,fig.width=20,fig.height=5}
carr_mn_graph <- graph_SWE_with_wateryear(carr_monthly, "Carrizo")
carr_mn_graph
```

```{r,fig.width=20,fig.height=5}
ch_mn_graph <- graph_SWE_with_wateryear(ch_monthly, "Chuska")
ch_mn_graph
```
```{r,fig.width=20,fig.height=5}
bm_mn_graph <- graph_SWE_with_wateryear(bm_monthly, "Black Mesa")
bm_mn_graph
```

